In [8]:
#import the necessary packages
import numpy as np
import cv2

image = cv2.imread("retina.jpg")
orig = image.copy()
gray1 = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray1 = gray1.astype(np.int16)
gray1 

print(gray1)
# perform a naive attempt to find the (x, y) coordinates of
# the area of the image with the largest intensity value

# apply a Gaussian blur to the image then find the brightest
# region
gray = cv2.GaussianBlur(gray1,(41,41),0)
(minVal, maxVal, minLoc, maxLoc) = cv2.minMaxLoc(gray)
image = orig.copy()
cv2.circle(image, (436,190), 41, (255, 0, 0), 2)
# display the results of our newly improved method
cv2.imshow("Robust", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[51 62 79 ... 21 67 45]
 [68 75 81 ... 15 26 16]
 [61 70 77 ... 12 22 33]
 ...
 [35 25  3 ... 30 11 20]
 [23 39 21 ... 47 37 43]
 [ 1 22 24 ... 35 38 72]]


In [2]:
gray1 = gray1 - 52
gray1

array([[ -1,  10,  27, ..., -31,  15,  -7],
       [ 16,  23,  29, ..., -37, -26, -36],
       [  9,  18,  25, ..., -40, -30, -19],
       ...,
       [-17, -27, -49, ..., -22, -41, -32],
       [-29, -13, -31, ...,  -5, -15,  -9],
       [-51, -30, -28, ..., -17, -14,  20]], dtype=int16)

In [3]:
maxLoc

(441, 187)

In [6]:
global Rightrow 
global Rightcol 
global Leftcol 
global Leftrow 
def kadane(arr, start, finish, n):

    Sum = 0
    maxSum = -999999999999
    i = None

    finish[0] = -1

    local_start = 0
 
    for i in range(n):
        Sum += arr[i]
        if Sum < 0:
            Sum = 0
            local_start = i + 1
        elif Sum > maxSum:
            maxSum = Sum
            start[0] = local_start
            finish[0] = i

    if finish[0] != -1:
        return maxSum

    maxSum = arr[0]
    start[0] = finish[0] = 0

    for i in range(1, n):
        if arr[i] > maxSum:
            maxSum = arr[i]
            start[0] = finish[0] = i
    return maxSum

def findMaxSum(M):
    global ROW, COL

    maxSum, finalLeft = -999999999999, None
    finalRight, finalTop, finalBottom = None, None, None
    left, right, i = None, None, None
 
    temp = [None] * ROW
    Sum = 0
    start = [0]
    finish = [0]

    for left in range(COL):

        temp = [0] * ROW

        for right in range(left, COL):

            for i in range(ROW):
                temp[i] += M[i][right]

            Sum = kadane(temp, start, finish, ROW)

            if Sum > maxSum:
                maxSum = Sum
                finalLeft = left
                finalRight = right
                finalTop = start[0]
                finalBottom = finish[0]
 
    # Prfinal values
    Leftrow = finalTop
    Leftcol = finalLeft    
    print("(Top, Left)", "(", finalTop,
          finalLeft, ")")
    Rightrow = finalRight
    Rightcol = finalBottom
    print("(Bottom, Right)", "(", finalBottom,
          finalRight, ")")
    print("Max sum is:", maxSum)
    
 
 
# Driver Code

ROW = 370
COL = 600

# Function call
findMaxSum(gray1)

(Top, Left) ( 164 409 )
(Bottom, Right) ( 217 464 )
Max sum is: 103486
